### DISCUSSION TITLE
Identify caller device

### DISCUSSION THREAD

**Discussion by dCypherNx** [samuelthng/t-house-blueprints#37] [Q&A]
Is there any way to identify witch device request script to run and then send notification to only this device ?

**Comment by samuelthng** [comment]
You can try to read the `wait.trigger` variable in your actions from a template to identify the source of the response.

<details>
<summary>Example: Using the `wait` variable in an action.</summary>

```yaml
alias: 🔔 My Test Notifications
use_blueprint:
  path: samuelthng/notifications.yaml
  input:
    message: Lalala
    notify_device: <redacted>
    confirm_action:
      # Just a dummy notification example that returns the content of the wait variable as the content of a notification.
      - service: notify.mobile_app_minion 
        metadata: {}
        data:
          message: |
            {% if not wait is defined %}
            Nothing
            {% else %}
            {{ wait.trigger }}
            {% endif %}
```
</details>

<details>
<summary>Example: `wait` variable content after a response is received.</summary>

```yaml
wait:
  remaining: 897.1542083369568
  trigger:
    id: '0'
    idx: '0'
    alias: null
    platform: event
    event:
      event_type: mobile_app_notification_action
      data:
        action_2_title: Option 2
        tag: script.my_test_notifications-01HMQQ28D7TM028FFFM91G39MM
        webhook_id: <redacted>
        channel: General
        message: Lalala
        action_1_title: Option 1
        action_1_key: FIRST_01HMQQ28D7TM028FFFM91G39MM
        action_2_key: SECOND_01HMQQ28D7TM028FFFM91G39MM
        visibility: private
        importance: default
        server_id: '6'
        action: FIRST_01HMQQ28D7TM028FFFM91G39MM # This tells you which option has been selected.
        device_id: <redacted> # This tells you which device responded
      origin: REMOTE
      time_fired: '2024-01-22T04:32:43.507952+00:00'
      context:
        id: <redacted>
        parent_id: null
        user_id: <redacted>
    description: event 'mobile_app_notification_action'
```
</details>

Example of response after clicking Option 1:
![image](https://github.com/samuelthng/t-house-blueprints/assets/19360561/840f4ac1-f068-4bde-b135-d7f187b5d6cc)
