### ISSUE TITLE
UndefinedError: 'None' has no attribute 'event'

### ISSUE THREAD

**Issue by m4dm4xi** [samuelthng/t-house-blueprints#43]
Hi Samuel,

I´m trying your script and I´m really astonished by what it is capable of.

However, at the moment I´m running into an error, which I can´t really pinpoint and which might be a timeout exception which isn´t caught properly.

I´m failing in this step of the script:
![image](https://github.com/samuelthng/t-house-blueprints/assets/42769944/3e44eba0-658e-4c55-a766-28a4f390c65c)

and the error which is thrown is: "UndefinedError: 'None' has no attribute 'event'"

The timeout is configured to 15min and it seems like the error is triggered after this timeout:
![image](https://github.com/samuelthng/t-house-blueprints/assets/42769944/c9a49629-f817-47f5-a55b-c3180d1d7f22)

It is very possible that the notification indeed timed out because actually one option was configured which then again didn´t show up on android. I havent found out yet why it wasn´t displayed.

I´m using 2.0.2 beta of the multi-device version. However, atm I´m only notifying one device.

Blueprint Config was:
```
alias: 🔔 Somebody goes to bed
use_blueprint:
  path: samuelthng/notifications.yaml
  input:
    notify_device:
      - 9c3bd60a496169fb77bb66b6cc3fd1c0
    title: EHS34 Bett
    subtitle: Jemand hat sich gerade hingelegt.
    message: Jemand hat sich gerade ins Bettchen gelegt.
    icon: mdi:bed-double
    confirm_option_mode: action
    confirm_text: Rolladen runter
    confirm_action:
      - service: cover.close_cover
        metadata: {}
        data: {}
        target:
          entity_id:
            - cover.jalou_sleep_left
            - cover.jalou_sleep_right
    dismiss_enabled: false
    run_timeout_actions: false
    attachment_type: camera_entity
    attachment_camera_entity: camera.wohnzimmer
icon: mdi:bed-double
```
